[project]
name = "lstm"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.4.1",
    "requests>=2.32.5",
    "scikit-learn>=1.7.2",
    "torch>=2.9.0",
    "torchao>=0.14.0",
    "torchvision>=0.24.0",
    "tqdm>=4.67.1",
]
